version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: product-explorer-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Magi
      POSTGRES_DB: product_explorer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product-explorer-network

  backend:
    build:
      context: ./backend
    container_name: product-explorer-backend
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: product_explorer
    ports:
      - "3001:3001"
    networks:
      - product-explorer-network

  # Optional: Redis for Queue (BullMQ) if needed later
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - product-explorer-network

networks:
  product-explorer-network:
    driver: bridge

volumes:
  postgres_data:
