services:
  - type: web
    name: product-explorer-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        value: 5432
      - key: DATABASE_USER
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_NAME
        value: product_explorer
      - key: PORT
        value: 3001

databases:
  - name: product-explorer-db
    databaseName: product_explorer
    user: postgres
    plan: free
