apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-backend
  template:
    metadata:
      labels:
        app: product-backend
    spec:
      containers:
        - name: product-backend
          image: gcr.io/REPLACE_IMAGE
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: user
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: product_explorer

---
apiVersion: v1
kind: Service
metadata:
  name: product-backend-service
spec:
  type: LoadBalancer
  selector:
    app: product-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
